version: '3.2'
networks:
  network: ~
services:
  nginx:
    depends_on:
      - backend
    networks:
      - network
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/config/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/certs/:/etc/nginx/certs
      - ./docker/nginx/htpasswd/:/etc/nginx/htpasswd
      - ./docker/nginx/templates/:/etc/nginx/templates
      - ./docker/nginx/logs/:/var/log/nginx
      - ./:/var/www
    environment:
      NGINX_BACKEND_UPSTREAM: backend:9000
  backend:
    networks:
      - network
    extra_hosts:
      - host.docker.internal:host-gateway
    container_name: backend
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
        UNAME: ${UNAME}
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
      - ./docker/php/config/my.ini:/usr/local/etc/php/conf.d/40-custom.ini
      - ./docker/php/logs/:/var/log/php/
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9000
      PHP_IDE_CONFIG: serverName=backend
    depends_on:
      - database
  database:
    networks:
      - network
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - database:/var/lib/mysql:rw
      - ./docker/mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/logs/:/var/log/mysql:rw
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
volumes:
  database:
